export const mockAgentReports = [
  {
    id: 1,
    name: 'Report Generator Alpha',
    status: 'active',
    tasksCompleted: 1243,
    tasksInProgress: 8,
    successRate: 98.5,
    avgExecutionTime: 2.3,
    lastReport: '2 min ago',
    memory: 45,
    cpu: 62,
  },
  {
    id: 2,
    name: 'Data Analyst Beta',
    status: 'active',
    tasksCompleted: 892,
    tasksInProgress: 3,
    successRate: 97.2,
    avgExecutionTime: 3.1,
    lastReport: '45 sec ago',
    memory: 38,
    cpu: 48,
  },
  {
    id: 3,
    name: 'Insight Engine Gamma',
    status: 'idle',
    tasksCompleted: 634,
    tasksInProgress: 0,
    successRate: 99.1,
    avgExecutionTime: 1.8,
    lastReport: '15 min ago',
    memory: 12,
    cpu: 8,
  },
  {
    id: 4,
    name: 'Report Validator Delta',
    status: 'warning',
    tasksCompleted: 456,
    tasksInProgress: 2,
    successRate: 94.3,
    avgExecutionTime: 4.2,
    lastReport: '5 min ago',
    memory: 71,
    cpu: 85,
  },
];